name: condo_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.2.0+7

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^1.17.0
  flutterfire_ui: ^0.4.0+5
  flutter_vlc_player: ^7.1.5
  flutter_vlc_player_platform_interface: ^2.0.1
  cloud_firestore_odm: ^1.0.0-dev.16
  json_annotation:
  provider: ^6.0.3
  cloud_firestore: ^3.1.16
  cloud_functions: ^3.2.15
  dart_ewelink_api:
    path: ../../../dart_ewelink_api
  firebase_auth: ^3.3.19
  package_info_plus: ^1.4.2
  url_launcher: ^6.1.3
  flutter_widget_from_html: ^0.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  cloud_firestore_odm_generator: ^1.0.0-dev.15
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
